<?php
// auto-generated by Kohana-Zend Autocomplete
// Developed by Peter Bowyer, Maple Design (http://www.mapledesign.co.uk/code/
// Last generated: 2012-07-16 12:37:39 CEST

// File D:/xampplite/htdocs/wadmin/system/controllers/captcha.php:
Class Captcha extends Captcha_Controller {}

// File D:/xampplite/htdocs/wadmin/system/controllers/template.php:
Class Your extends Your_Controller { function __construct(); }

// File D:/xampplite/htdocs/wadmin/system/helpers/arr.php:
Class arr extends arr_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/cookie.php:
Class cookie extends cookie_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/date.php:
Class date extends date_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/download.php:
Class download extends download_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/email.php:
Class email extends email_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/expires.php:
Class expires extends expires_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/feed.php:
Class feed extends feed_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/file.php:
Class file extends file_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/form.php:
Class form extends form_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/format.php:
Class format extends format_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/html.php:
Class html extends html_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/inflector.php:
Class inflector extends inflector_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/num.php:
Class num extends num_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/remote.php:
Class remote extends remote_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/request.php:
Class request extends request_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/security.php:
Class security extends security_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/text.php:
Class text extends text_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/upload.php:
Class upload extends upload_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/url.php:
Class url extends url_Core {}

// File D:/xampplite/htdocs/wadmin/system/helpers/valid.php:
Class valid extends valid_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/Calendar.php:
Class Calendar extends Calendar_Core { function __construct($month = NULL, $year = NULL); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Calendar_Event.php:
Class Calendar_Event extends Calendar_Event_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/Captcha.php:
Class Captcha extends Captcha_Core { function __construct($group = NULL); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Database.php:
Class Database extends Database_Core { function __construct($config = array()); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Encrypt.php:
Class Encrypt extends Encrypt_Core { function __construct($config = FALSE); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Input.php:
Class Input extends Input_Core { function __construct(); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Model.php:
Class Model extends Model_Core { function __construct(); }

// File D:/xampplite/htdocs/wadmin/system/libraries/ORM.php:
Class ORM extends ORM_Core { function __construct($id = NULL); }

// File D:/xampplite/htdocs/wadmin/system/libraries/ORM_Iterator.php:
Class ORM_Iterator extends ORM_Iterator_Core { function __construct(ORM $model, Database_Result $result); }

// File D:/xampplite/htdocs/wadmin/system/libraries/ORM_Tree.php:
Class ORM_Tree extends ORM_Tree_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/ORM_Versioned.php:
Class ORM_Versioned extends ORM_Versioned_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/Pagination.php:
Class Pagination extends Pagination_Core { function __construct($config = array()); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Profiler.php:
Class Profiler extends Profiler_Core { function __construct(); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Profiler_Table.php:
Class Profiler_Table extends Profiler_Table_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/Router.php:
Class Router extends Router_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/Session.php:
Class Session extends Session_Core { function __construct(); }

// File D:/xampplite/htdocs/wadmin/system/libraries/Tagcloud.php:
Class Tagcloud extends Tagcloud_Core { function __construct(array $elements, $min_size = NULL, $max_size = NULL, $shuffle = FALSE); }

// File D:/xampplite/htdocs/wadmin/system/libraries/URI.php:
Class URI extends URI_Core {}

// File D:/xampplite/htdocs/wadmin/system/libraries/Validation.php:
Class Validation extends Validation_Core { function __construct(array $array); }

// File D:/xampplite/htdocs/wadmin/system/libraries/View.php:
Class View extends View_Core { function __construct($name = NULL, $data = NULL, $type = NULL); }

// File D:/xampplite/htdocs/wadmin/modules/formo/controllers/formo_demo.php:
Class Formo_demo extends Formo_demo_Controller { function __construct(); }

// File D:/xampplite/htdocs/wadmin/modules/formo/libraries/Formo.php:
Class Formo extends Formo_Core { function __construct($name='formo',$type=''); }

// File D:/xampplite/htdocs/wadmin/modules/formo/libraries/Formo_Element.php:
Class Formo_Element extends Formo_Element_Core { function __construct($name='',$info=array()); }

// File D:/xampplite/htdocs/wadmin/modules/formo/libraries/Formo_Group.php:
Class Formo_Group extends Formo_Group_Core { function __construct($name, $values, $info=array()); }

// File D:/xampplite/htdocs/wadmin/modules/media/controllers/media.php:
Class Media extends Media_Controller { function __construct(); }

// File D:/xampplite/htdocs/wadmin/modules/media/helpers/media.php:
Class media extends media_Core {}

// File D:/xampplite/htdocs/wadmin/modules/media/libraries/JavaScriptPacker.php:
Class JavaScriptPacker extends JavaScriptPacker_Core { function __construct($_script, $_encoding = 62, $_fastDecode = true, $_specialChars = false); }

// File D:/xampplite/htdocs/wadmin/modules/kodoc/controllers/kodoc.php:
Class Kodoc extends Kodoc_Controller { function __construct(); }

// File D:/xampplite/htdocs/wadmin/modules/kodoc/libraries/Kodoc.php:
Class Kodoc extends Kodoc_Core { function __construct($type, $filename); }

// File D:/xampplite/htdocs/wadmin/modules/auth/libraries/Auth.php:
Class Auth extends Auth_Core { function __construct($config = array()); }

// File D:/xampplite/htdocs/wadmin/application/controllers/addressing.php:
Class Addressing extends Addressing_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/catalogue.php:
Class Catalogue extends Catalogue_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/conspectus.php:
Class Conspectus extends Conspectus_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/home.php:
Class Home extends Home_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/login.php:
Class Login extends Login_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/progress.php:
Class Progress extends Progress_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/quality_control.php:
Class Quality_Control extends Quality_Control_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/rate.php:
Class Rate extends Rate_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/suggest.php:
Class Suggest extends Suggest_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/table.php:
Class Table extends Table_Controller { function __construct(); }

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/conspectus_table.php:
Class Conspectus_Table extends Conspectus_Table_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/contacts.php:
Class Contacts extends Contacts_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/contracts.php:
Class Contracts extends Contracts_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/correspondence.php:
Class Correspondence extends Correspondence_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/curators.php:
Class Curators extends Curators_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/publishers.php:
Class Publishers extends Publishers_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/ratings.php:
Class Ratings extends Ratings_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/resources.php:
Class Resources extends Resources_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/tables/seeds.php:
Class Seeds extends Seeds_Controller {}

// File D:/xampplite/htdocs/wadmin/application/controllers/template.php:
Class Your extends Your_Controller { function __construct() {
        $this->session = Session::instance();
        
        parent::__construct();

        // load constants from config/constants.php file
        Kohana::config_load('constants');

        // Load the template
        $this->template = new View($this->template);

        if ($this->auto_render == TRUE) {
            // Render the template immediately after the controller method
            Event::add('system.post_controller', array(
                    $this ,
                    '_render'));
        }

        if (! empty($this->title)) {
            $this->template->title = $this->title;
        } else {
            $this->template->title = " | ";
        }

        $this->template->message = $this->session->get_once('message');
        $this->template->content = View::factory("layout/center");
        $this->template->top_nav = View::factory("layout/top_nav");
        $this->template->left_nav = View::factory("layout/left_nav");
        $this->template->right_column = View::factory('layout/right_column'); }

// File D:/xampplite/htdocs/wadmin/application/controllers/zend_autocomplete.php:
Class Zend_Autocomplete extends Zend_Autocomplete_Controller {}

// File D:/xampplite/htdocs/wadmin/application/libraries/Pagination.php:
Class Pagination extends Pagination_Core { function __construct($config = array()); }

