<?php
// auto-generated by Kohana-Zend Autocomplete
// Developed by Peter Bowyer, Maple Design (http://www.mapledesign.co.uk/code/
// Last generated: 2009-08-12 21:11:09 CEST

// File /var/www/wadmin/system/controllers/captcha.php:
Class Captcha extends Captcha_Controller {}

// File /var/www/wadmin/system/controllers/template.php:
Class Your extends Your_Controller { function __construct(); }

// File /var/www/wadmin/system/helpers/arr.php:
Class arr extends arr_Core {}

// File /var/www/wadmin/system/helpers/cookie.php:
Class cookie extends cookie_Core {}

// File /var/www/wadmin/system/helpers/date.php:
Class date extends date_Core {}

// File /var/www/wadmin/system/helpers/download.php:
Class download extends download_Core {}

// File /var/www/wadmin/system/helpers/email.php:
Class email extends email_Core {}

// File /var/www/wadmin/system/helpers/expires.php:
Class expires extends expires_Core {}

// File /var/www/wadmin/system/helpers/feed.php:
Class feed extends feed_Core {}

// File /var/www/wadmin/system/helpers/file.php:
Class file extends file_Core {}

// File /var/www/wadmin/system/helpers/format.php:
Class format extends format_Core {}

// File /var/www/wadmin/system/helpers/form.php:
Class form extends form_Core {}

// File /var/www/wadmin/system/helpers/html.php:
Class html extends html_Core {}

// File /var/www/wadmin/system/helpers/inflector.php:
Class inflector extends inflector_Core {}

// File /var/www/wadmin/system/helpers/num.php:
Class num extends num_Core {}

// File /var/www/wadmin/system/helpers/remote.php:
Class remote extends remote_Core {}

// File /var/www/wadmin/system/helpers/request.php:
Class request extends request_Core {}

// File /var/www/wadmin/system/helpers/security.php:
Class security extends security_Core {}

// File /var/www/wadmin/system/helpers/text.php:
Class text extends text_Core {}

// File /var/www/wadmin/system/helpers/upload.php:
Class upload extends upload_Core {}

// File /var/www/wadmin/system/helpers/url.php:
Class url extends url_Core {}

// File /var/www/wadmin/system/helpers/valid.php:
Class valid extends valid_Core {}

// File /var/www/wadmin/system/libraries/Calendar_Event.php:
Class Calendar_Event extends Calendar_Event_Core {}

// File /var/www/wadmin/system/libraries/Calendar.php:
Class Calendar extends Calendar_Core { function __construct($month = NULL, $year = NULL); }

// File /var/www/wadmin/system/libraries/Captcha.php:
Class Captcha extends Captcha_Core { function __construct($group = NULL); }

// File /var/www/wadmin/system/libraries/Database.php:
Class Database extends Database_Core { function __construct($config = array()); }

// File /var/www/wadmin/system/libraries/Encrypt.php:
Class Encrypt extends Encrypt_Core { function __construct($config = FALSE); }

// File /var/www/wadmin/system/libraries/Input.php:
Class Input extends Input_Core { function __construct(); }

// File /var/www/wadmin/system/libraries/Model.php:
Class Model extends Model_Core { function __construct(); }

// File /var/www/wadmin/system/libraries/ORM_Iterator.php:
Class ORM_Iterator extends ORM_Iterator_Core { function __construct(ORM $model, Database_Result $result); }

// File /var/www/wadmin/system/libraries/ORM.php:
Class ORM extends ORM_Core { function __construct($id = NULL); }

// File /var/www/wadmin/system/libraries/ORM_Tree.php:
Class ORM_Tree extends ORM_Tree_Core {}

// File /var/www/wadmin/system/libraries/ORM_Versioned.php:
Class ORM_Versioned extends ORM_Versioned_Core {}

// File /var/www/wadmin/system/libraries/Pagination.php:
Class Pagination extends Pagination_Core { function __construct($config = array()); }

// File /var/www/wadmin/system/libraries/Profiler.php:
Class Profiler extends Profiler_Core { function __construct(); }

// File /var/www/wadmin/system/libraries/Profiler_Table.php:
Class Profiler_Table extends Profiler_Table_Core {}

// File /var/www/wadmin/system/libraries/Router.php:
Class Router extends Router_Core {}

// File /var/www/wadmin/system/libraries/Session.php:
Class Session extends Session_Core { function __construct(); }

// File /var/www/wadmin/system/libraries/Tagcloud.php:
Class Tagcloud extends Tagcloud_Core { function __construct(array $elements, $min_size = NULL, $max_size = NULL, $shuffle = FALSE); }

// File /var/www/wadmin/system/libraries/URI.php:
Class URI extends URI_Core {}

// File /var/www/wadmin/system/libraries/Validation.php:
Class Validation extends Validation_Core { function __construct(array $array); }

// File /var/www/wadmin/system/libraries/View.php:
Class View extends View_Core { function __construct($name = NULL, $data = NULL, $type = NULL); }

// File /var/www/wadmin/modules/formo/controllers/formo_demo.php:
Class Formo_demo extends Formo_demo_Controller { function __construct(); }

// File /var/www/wadmin/modules/formo/libraries/Formo_Element.php:
Class Formo_Element extends Formo_Element_Core { function __construct($name='',$info=array()); }

// File /var/www/wadmin/modules/formo/libraries/Formo_Group.php:
Class Formo_Group extends Formo_Group_Core { function __construct($name, $values, $info=array()); }

// File /var/www/wadmin/modules/formo/libraries/Formo.php:
Class Formo extends Formo_Core { function __construct($name='formo',$type=''); }

// File /var/www/wadmin/modules/media/controllers/media.php:
Class Media extends Media_Controller { function __construct(); }

// File /var/www/wadmin/modules/media/helpers/media.php:
Class media extends media_Core {}

// File /var/www/wadmin/modules/media/libraries/JavaScriptPacker.php:
Class JavaScriptPacker extends JavaScriptPacker_Core { function __construct($_script, $_encoding = 62, $_fastDecode = true, $_specialChars = false); }

// File /var/www/wadmin/modules/kodoc/controllers/kodoc.php:
Class Kodoc extends Kodoc_Controller { function __construct(); }

// File /var/www/wadmin/modules/kodoc/libraries/Kodoc.php:
Class Kodoc extends Kodoc_Core { function __construct($type, $filename); }

// File /var/www/wadmin/modules/forge/controllers/forge_demo.php:
Class Forge_demo extends Forge_demo_Controller {}

// File /var/www/wadmin/modules/forge/libraries/Forge.php:
Class Forge extends Forge_Core { function __construct($action = NULL, $title = '', $method = NULL, $attr = array()); }

// File /var/www/wadmin/modules/forge/libraries/Form_Button.php:
Class Form_Button extends Form_Button_Core { function __construct($value); }

// File /var/www/wadmin/modules/forge/libraries/Form_Dateselect.php:
Class Form_Dateselect extends Form_Dateselect_Core { function __construct($name); }

// File /var/www/wadmin/modules/forge/libraries/Form_Dropdown.php:
Class Form_Dropdown extends Form_Dropdown_Core {}

// File /var/www/wadmin/modules/forge/libraries/Form_Group.php:
Class Form_Group extends Form_Group_Core { function __construct($name = NULL, $class = 'group'); }

// File /var/www/wadmin/modules/forge/libraries/Form_Hidden.php:
Class Form_Hidden extends Form_Hidden_Core {}

// File /var/www/wadmin/modules/forge/libraries/Form_Checkbox.php:
Class Form_Checkbox extends Form_Checkbox_Core {}

// File /var/www/wadmin/modules/forge/libraries/Form_Checklist.php:
Class Form_Checklist extends Form_Checklist_Core { function __construct($name); }

// File /var/www/wadmin/modules/forge/libraries/Form_Input.php:
Class Form_Input extends Form_Input_Core { function __construct($name); }

// File /var/www/wadmin/modules/forge/libraries/Form_Password.php:
Class Form_Password extends Form_Password_Core {}

// File /var/www/wadmin/modules/forge/libraries/Form_Phonenumber.php:
Class Form_Phonenumber extends Form_Phonenumber_Core { function __construct($name); }

// File /var/www/wadmin/modules/forge/libraries/Form_Radiolist.php:
Class Form_Checklist extends Form_Checklist_Core { function __construct($name); }

// File /var/www/wadmin/modules/forge/libraries/Form_Radio.php:
Class Form_Radio extends Form_Radio_Core {}

// File /var/www/wadmin/modules/forge/libraries/Form_Submit.php:
Class Form_Submit extends Form_Submit_Core { function __construct($value, $name = ''); }

// File /var/www/wadmin/modules/forge/libraries/Form_Textarea.php:
Class Form_Textarea extends Form_Textarea_Core {}

// File /var/www/wadmin/modules/forge/libraries/Form_Upload.php:
Class Form_Upload extends Form_Upload_Core { function __construct($name, $filename = FALSE); }

// File /var/www/wadmin/modules/auth/libraries/Auth.php:
Class Auth extends Auth_Core { function __construct($config = array()); }

// File /var/www/wadmin/application/controllers/addressing.php:
Class Addressing extends Addressing_Controller {}

// File /var/www/wadmin/application/controllers/auth.php:
Class Auth extends Auth_Controller {}

// File /var/www/wadmin/application/controllers/catalogue.php:
Class Catalogue extends Catalogue_Controller {}

// File /var/www/wadmin/application/controllers/home.php:
Class Home extends Home_Controller {}

// File /var/www/wadmin/application/controllers/login.php:
Class Login extends Login_Controller {}

// File /var/www/wadmin/application/controllers/progress.php:
Class Progress extends Progress_Controller {}

// File /var/www/wadmin/application/controllers/quality_control.php:
Class Quality_Control extends Quality_Control_Controller {}

// File /var/www/wadmin/application/controllers/rate.php:
Class Rate extends Rate_Controller {}

// File /var/www/wadmin/application/controllers/suggest.php:
Class Suggest extends Suggest_Controller {}

// File /var/www/wadmin/application/controllers/table.php:
Class Table extends Table_Controller { function __construct(); }

// File /var/www/wadmin/application/controllers/tables/contacts.php:
Class Contacts extends Contacts_Controller {}

// File /var/www/wadmin/application/controllers/tables/contracts.php:
Class Contracts extends Contracts_Controller {}

// File /var/www/wadmin/application/controllers/tables/correspondence.php:
Class Correspondence extends Correspondence_Controller {}

// File /var/www/wadmin/application/controllers/tables/curators.php:
Class Curators extends Curators_Controller {}

// File /var/www/wadmin/application/controllers/tables/publishers.php:
Class Publishers extends Publishers_Controller {}

// File /var/www/wadmin/application/controllers/tables/ratings.php:
Class Ratings extends Ratings_Controller {}

// File /var/www/wadmin/application/controllers/tables/resources.php:
Class Resources extends Resources_Controller {}

// File /var/www/wadmin/application/controllers/tables/seeds.php:
Class Seeds extends Seeds_Controller {}

// File /var/www/wadmin/application/controllers/template.php:
Class Your extends Your_Controller { function __construct(); }

// File /var/www/wadmin/application/controllers/zend_autocomplete.php:
Class Zend_Autocomplete extends Zend_Autocomplete_Controller {}

