<?php
// auto-generated by Kohana-Zend Autocomplete
// Developed by Peter Bowyer, Maple Design (http://www.mapledesign.co.uk/code/
// Last generated: 2008-08-14 13:50:34

// File /var/www/wa/system/controllers/template.php:
Class Your extends Your_Controller { function __construct(); }

// File /var/www/wa/system/libraries/Calendar.php:
Class Calendar extends Calendar_Core { function __construct($month = NULL, $year = NULL); }

// File /var/www/wa/system/libraries/Captcha.php:
Class Captcha extends Captcha_Core { function __construct($group = NULL); }

// File /var/www/wa/system/libraries/Database.php:
Class Database extends Database_Core { function __construct($config = array()); }

// File /var/www/wa/system/libraries/Encrypt.php:
Class Encrypt extends Encrypt_Core { function __construct($config = FALSE); }

// File /var/www/wa/system/libraries/Input.php:
Class Input extends Input_Core { function __construct(); }

// File /var/www/wa/system/libraries/Model.php:
Class Model extends Model_Core { function __construct(); }

// File /var/www/wa/system/libraries/ORM_Iterator.php:
Class ORM_Iterator extends ORM_Iterator_Core { function __construct(ORM $model, $result); }

// File /var/www/wa/system/libraries/ORM.php:
Class ORM extends ORM_Core { function __construct($id = NULL); }

// File /var/www/wa/system/libraries/Pagination.php:
Class Pagination extends Pagination_Core { function __construct($config = array()); }

// File /var/www/wa/system/libraries/Profiler.php:
Class Profiler extends Profiler_Core { function __construct(); }

// File /var/www/wa/system/libraries/Session.php:
Class Session extends Session_Core { function __construct(); }

// File /var/www/wa/system/libraries/Validation.php:
Class Validation extends Validation_Core { function __construct(array $array); }

// File /var/www/wa/system/libraries/View.php:
Class View extends View_Core { function __construct($name = NULL, $data = NULL, $type = NULL); }

// File /var/www/wa/modules/user_guide/controllers/user_guide.php:
Class User_Guide extends User_Guide_Controller { function __construct(); }

// File /var/www/wa/modules/media/controllers/media.php:
Class Media extends Media_Controller { function __construct(); }

// File /var/www/wa/modules/media/libraries/JavaScriptPacker.php:
Class JavaScriptPacker extends JavaScriptPacker_Core { function __construct($_script, $_encoding = 62, $_fastDecode = true, $_specialChars = false); }

// File /var/www/wa/modules/kodoc/controllers/kodoc.php:
Class Kodoc extends Kodoc_Controller { function __construct(); }

// File /var/www/wa/modules/kodoc/libraries/Kodoc.php:
Class Kodoc extends Kodoc_Core { function __construct($type, $filename); }

// File /var/www/wa/modules/forge/libraries/Forge.php:
Class Forge extends Forge_Core { function __construct($action = NULL, $title = '', $method = NULL, $attr = array()); }

// File /var/www/wa/modules/forge/libraries/Form_Dateselect.php:
Class Form_Dateselect extends Form_Dateselect_Core { function __construct($name); }

// File /var/www/wa/modules/forge/libraries/Form_Group.php:
Class Form_Group extends Form_Group_Core { function __construct($name = NULL, $class = 'group'); }

// File /var/www/wa/modules/forge/libraries/Form_Checklist.php:
Class Form_Checklist extends Form_Checklist_Core { function __construct($name); }

// File /var/www/wa/modules/forge/libraries/Form_Input.php:
Class Form_Input extends Form_Input_Core { function __construct($name); }

// File /var/www/wa/modules/forge/libraries/Form_Phonenumber.php:
Class Form_Phonenumber extends Form_Phonenumber_Core { function __construct($name); }

// File /var/www/wa/modules/forge/libraries/Form_Submit.php:
Class Form_Submit extends Form_Submit_Core { function __construct($value); }

// File /var/www/wa/modules/forge/libraries/Form_Upload.php:
Class Form_Upload extends Form_Upload_Core { function __construct($name, $filename = FALSE); }

// File /var/www/wa/modules/auth/libraries/Auth.php:
Class Auth extends Auth_Core { function __construct($config = array()); }

// File /var/www/wa/application/controllers/table.php:
Class Table extends Table_Controller { function __construct(); }

// File /var/www/wa/application/controllers/template.php:
Class Your extends Your_Controller { function __construct(); }

